### ISSUE TITLE
Parser is not working properly

### ISSUE THREAD

**Issue by RaTB0t5** [KINGSABRI/nipper_parser#4]
i tried load my nipper studio xml report, but the output is showing some error 
```
root@kali:~/nipper_parser/lib# ruby nipper_parser.rb dummy-sw.xml 
/root/nipper_parser/lib/nipper_parser/parsers/security_audit.rb:149:in `block in findings': undefined method `elements' for nil:NilClass (NoMethodError)
	from /root/nipper_parser/lib/nipper_parser/parsers/security_audit.rb:139:in `map'
	from /root/nipper_parser/lib/nipper_parser/parsers/security_audit.rb:139:in `findings'
	from /root/nipper_parser/lib/nipper_parser/parsers/security_audit.rb:108:in `initialize'
	from nipper_parser.rb:55:in `new'
	from nipper_parser.rb:55:in `initialize'
	from nipper_parser.rb:67:in `new'
	from nipper_parser.rb:67:in `<main>'

root@kali:~/nipper_parser/lib/nipper_parser/parsers# ruby security_audit.rb dummy-sw.xml 
security_audit.rb:149:in `block in findings': undefined method `elements' for nil:NilClass (NoMethodError)
	from security_audit.rb:139:in `map'
	from security_audit.rb:139:in `findings'
	from security_audit.rb:108:in `initialize'
	from security_audit.rb:295:in `new'
	from security_audit.rb:295:in `<main>'

```
Im not able to get the excat out as u mentioned in the readme file.kindly help me....

**Comment by KINGSABRI** [comment]
Hello there
Would you share the `nipper_parser.rb` and `security_audit.rb` scripts you are using?

**Comment by KINGSABRI** [comment]
hmm just noticed from your terminal that you're not using it as a library, you use the inside `security_audit.rb` file which is not recommended because it tends to be for testing.

Please install `gem install nipper_parser` and use [this](https://github.com/KINGSABRI/nipper_parser#usage) way to use the gem

**Comment by RaTB0t5** [comment]
Ok Thank you So much KingSABRI

**Comment by RaTB0t5** [comment]
Can you help me !! how to execute a sample dummy XML parser... can you add the command line here?
if possible.

**Comment by KINGSABRI** [comment]
Hey! 
It's not a commandline tool it a library but tell me what do you want to do exactly to help you? what kind of outputs do you need?
